#!/usr/bin/env bash
# copy a file from client to server using scp
#
# $1: path to source file
# $2: IP of receiving server
# $3: username scp connects with
# $4: path to SSH private key

if (( $# < 4 ));
then
	echo "Usage: 0-transfer_file PATH_TO_FILE_IP IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2:~/"
fi
