#!/usr/bin/env bash
# install Nginx web server with forced 'Y' flags for remote server

apt-get update
apt-get -y install nginx
mkdir -p /var/www/html
echo "Holberton School" > /var/www/html/index.html
service nginx reload
service nginx restart
