#!/usr/bin/env bash
# print a string 10 times and on the 9th iteration print another string

declare -i idx=0
while (( idx < 10 ))
do
	echo "Holberton School"
	if (( idx == 8 ))
	then
		echo "Hi"
	fi
	(( idx++ ))
done
