#!/usr/bin/env bash
# loops to 10 and print different strings at certain iterations

declare -i idx=0
while (( idx < 10 ))
do
	if (( idx == 3 ))
	then
		echo "bad luck"
	elif (( idx == 7 ))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	(( idx++ ))
done
