#!/usr/bin/env bash
# prints numbers with different outputs at 4th, 9th, and 17th iterations

declare -i idx=0
while (( idx < 21 ))
do
	echo "$idx"
	case "$idx" in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	(( idx++ ))
done
